server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: inventory-service
            uri: lb://INVENTORY-SERVICE
            predicates:
              - Path=/inventory/**