server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
       routes:
          - id: inventory-service
            uri: http://localhost:40359
            predicates:
              - Path=/inventory/**