spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: customer_user
    password: customer_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0
