spring:
  application:
    name: report-service

  datasource:
    url: jdbc:postgresql://localhost:5432/report_db
    username: report_user
    password: report_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0
